### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by enandr** [enandr/wicked-sales#23]
- [x] fix spacing on mobile cart in landscape
- [x] add padding to left of image in cart
- [x] add padding on top and bottom in cart
- [x] try and sync timers (decided i like the current timer system now)
